import type { Service } from '@/types/content'

export const services: Service[] = [
  {
    slug: 'ai-chatbots-agents',
    icon: 'Bot',
    title: 'AI Chatbots & Agents',
    subtitle: 'Your 24/7 AI Employee.',
    desc: 'Custom AI assistants trained on your business — answering customers, qualifying leads, and booking appointments on your website and WhatsApp, around the clock.',
    features: [
      'Custom AI trained on your business data',
      'Website + WhatsApp AI chat',
      'Lead qualification & appointment booking',
      'Human handoff for complex queries',
      'Multilingual — Hindi + English',
      'Monthly tuning & analytics',
    ],
    price: 'Custom — free consult',
    timeline: '1–2 weeks',
    badge: 'AI',
  },
  {
    slug: 'ai-workflow-automation',
    icon: 'Workflow',
    title: 'AI Workflow Automation',
    subtitle: 'If You Do It Twice, AI Does It Forever.',
    desc: 'Connect your tools — Sheets, WhatsApp, email, CRM — with AI in the middle. Auto-draft replies, summarize enquiries, generate reports, route leads. Zero clicks.',
    features: [
      'AI-powered pipelines (n8n / Make / custom)',
      'Auto-draft email & WhatsApp replies',
      'Document & enquiry summarization',
      'Smart lead scoring & routing',
      'Connects 100+ apps via API',
      'Runs 24/7 on autopilot',
    ],
    price: 'Custom — free consult',
    timeline: '1–2 weeks',
    badge: 'AI',
  },
  {
    slug: 'website-development',
    icon: 'Globe',
    title: 'Website Development',
    subtitle: 'Beautiful. Fast. Converting.',
    desc: 'Custom websites with Next.js, React and WordPress — blazing fast, SEO-optimized, and built to convert visitors into customers. Mobile-first, always.',
    features: [
      'Custom Next.js / React / WordPress',
      'Mobile-first responsive design',
      'Core Web Vitals optimized (95+ Lighthouse)',
      'On-page SEO setup included',
      'CMS integration',
      '30-day post-launch support',
    ],
    price: 'Starting ₹9,999',
    timeline: '1–2 weeks',
    badge: 'POPULAR',
  },
  {
    slug: 'app-development',
    icon: 'Smartphone',
    title: 'App Development',
    subtitle: 'iOS & Android. One Codebase.',
    desc: 'Cross-platform apps with React Native and Flutter. From MVP to full product — we ship apps users genuinely enjoy using.',
    features: [
      'React Native / Flutter',
      'iOS & Android deployment',
      'REST API integration',
      'Push notifications',
      'App Store submission',
      'Performance optimization',
    ],
    price: 'Starting ₹24,999',
    timeline: '4–6 weeks',
  },
  {
    slug: 'whatsapp-automation',
    icon: 'MessageSquare',
    title: 'WhatsApp Automation',
    subtitle: 'Automate. Engage. Convert.',
    desc: 'Integrate WhatsApp Business API to automate support, send order updates, qualify leads, and run campaigns — all on autopilot.',
    features: [
      'WhatsApp Business API setup',
      'Automated chatbot flows',
      'Broadcast campaigns',
      'Google Sheet sync',
      'Lead capture & qualification',
      'Analytics dashboard',
    ],
    price: 'Starting ₹4,999',
    timeline: '3–5 days',
  },
  {
    slug: 'google-sheet-automation',
    icon: 'FileSpreadsheet',
    title: 'Google Sheet Automation',
    subtitle: 'Kill Manual Work. Forever.',
    desc: 'Eliminate manual data entry forever. Custom Apps Script automations that connect your sheets to WhatsApp, email, forms and any API.',
    features: [
      'Custom Apps Script development',
      'Auto-reports & dashboards',
      'Form → Sheet → WhatsApp pipelines',
      'Email triggers & alerts',
      'API integrations',
      'Zero manual data entry',
    ],
    price: 'Starting ₹2,999',
    timeline: '2–4 days',
  },
  {
    slug: 'social-media-management',
    icon: 'Share2',
    title: 'Social Media Management',
    subtitle: 'Grow Your Audience. Daily.',
    desc: 'Content, creatives & profile optimization that grow your brand on Instagram, Facebook & LinkedIn — proven with real local businesses.',
    features: [
      'Content calendar & posting',
      'Reels & creative design',
      'Profile / page optimization',
      'Hashtag & caption strategy',
      'Monthly growth reports',
      'Community engagement',
    ],
    price: 'Starting ₹5,999/mo',
    timeline: 'Ongoing monthly',
  },
  {
    slug: 'branding-logo-design',
    icon: 'Palette',
    title: 'Branding & Logo Design',
    subtitle: 'Look Like a Million Bucks.',
    desc: 'Logos, brand kits, UI/UX & marketing assets that make you look like a ₹1Cr company. We rebuilt Ankita Beauty Salon and built Grafiya from scratch.',
    features: [
      'Logo design & rebuilds',
      'Complete brand kits',
      'Social media templates',
      'Business cards & stationery',
      'Brand guidelines doc',
      'Unlimited revisions till you love it',
    ],
    price: 'Starting ₹1,999',
    timeline: '3–5 days',
  },
  {
    slug: 'meta-ads',
    icon: 'TrendingUp',
    title: 'Meta Ads & Performance Marketing',
    subtitle: 'Paid Reach. Real Results.',
    desc: 'Facebook & Instagram ad campaigns engineered for leads and sales — strategy, creatives, targeting and weekly optimization.',
    features: [
      'Campaign strategy & setup',
      'Ad creative design',
      'Audience targeting & retargeting',
      'Pixel & conversion tracking',
      'A/B testing',
      'Weekly performance reports',
    ],
    price: 'Starting ₹4,999/mo + ad spend',
    timeline: 'Ongoing monthly',
  },
  {
    slug: 'google-business-setup',
    icon: 'MapPin',
    title: 'Google Business Setup',
    subtitle: 'Dominate Local Search.',
    desc: 'Show up first when customers search for your service nearby. Complete Google Business Profile setup and local SEO.',
    features: [
      'Profile creation & verification',
      'Photos, services & posts setup',
      'Review strategy',
      'Local SEO optimization',
      'Q&A section setup',
      'Maps ranking improvement',
    ],
    price: 'Starting ₹1,499',
    timeline: '1–2 days',
  },
  {
    slug: 'email-automation',
    icon: 'Mail',
    title: 'Email Automation',
    subtitle: 'Nurture Leads While You Sleep.',
    desc: 'Drip sequences that nurture leads and close deals on autopilot — welcome flows, follow-ups, and campaigns.',
    features: [
      'Drip sequence design',
      'Welcome & follow-up flows',
      'Newsletter setup',
      'SMTP / domain configuration',
      'Open & click analytics',
      'CRM integration',
    ],
    price: 'Starting ₹3,999',
    timeline: '3–5 days',
  },
  {
    slug: 'data-dashboards',
    icon: 'BarChart3',
    title: 'Data & Dashboards',
    subtitle: 'Your Data. Your Power.',
    desc: 'Clean pipelines, smart dashboards, and real-time reports for data-driven decisions — built on Sheets, Looker Studio or custom.',
    features: [
      'Data cleaning & pipelines',
      'Looker Studio dashboards',
      'Real-time reporting',
      'KPI tracking setup',
      'Multi-source integration',
      'Team training included',
    ],
    price: 'Starting ₹3,499',
    timeline: '3–7 days',
  },
]

export const getService = (slug: string) => services.find((s) => s.slug === slug)
