import type { Service } from '@/types/content'

export const services: Service[] = [
  {
    slug: 'website-development',
    icon: 'Globe',
    title: 'Website Development',
    subtitle: 'Site. Landing Pages. Admin Panel.',
    desc: 'Custom websites and landing pages built with Next.js, React and WordPress — connected to an admin panel so you update content yourself, with your data saved to Google Sheets or Supabase.',
    image: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=900&q=80&auto=format&fit=crop',
    features: [
      'Custom Next.js / React / WordPress builds',
      'Landing pages connected to your main site',
      'Admin panel — update content yourself',
      'Google Sheets / Supabase data backend',
      'Mobile-first, 95+ Lighthouse, on-page SEO',
      '30-day post-launch support',
    ],
    price: 'Starting ₹9,999',
    timeline: '1–2 weeks',
    badge: 'POPULAR',
    related: ['business-automation', 'branding-logo-design', 'google-business-setup'],
  },
  {
    slug: 'business-automation',
    icon: 'Workflow',
    title: 'Business Automation',
    subtitle: 'If You Do It Twice, Automate It Forever.',
    desc: 'One system, four engines — Google Sheet automation, AI workflow automation, WhatsApp automation and email automation. Your enquiries, follow-ups, reports and campaigns run on autopilot, 24/7.',
    image: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=900&q=80&auto=format&fit=crop',
    features: [
      'Google Sheet automation — Apps Script, zero manual entry',
      'AI workflow automation — n8n / Make / custom pipelines',
      'WhatsApp automation — chatbot flows, broadcasts, API setup',
      'Email automation — drips, follow-ups, newsletters',
      'Form → Sheet → WhatsApp → Email pipelines',
      'Auto-reports, dashboards & smart lead routing',
    ],
    price: 'Starting ₹2,999',
    timeline: '3–7 days',
    badge: 'AI',
    related: ['website-development', 'google-business-setup'],
  },
  {
    slug: 'social-media-management',
    icon: 'Share2',
    title: 'Social Media Management',
    subtitle: 'Creative Posts. Reels. Growth.',
    desc: 'Creative posts and reels made for your brand, plus profile optimization and posting strategy that grow you on Instagram, Facebook & LinkedIn — proven with real local businesses.',
    image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=900&q=80&auto=format&fit=crop',
    features: [
      'Creative post & reel production',
      'Content calendar & posting',
      'Profile / page optimization',
      'Hashtag & caption strategy',
      'Monthly growth reports',
      'Community engagement',
    ],
    price: 'Starting ₹5,999/mo',
    timeline: 'Ongoing monthly',
    related: ['branding-logo-design', 'meta-ads'],
  },
  {
    slug: 'branding-logo-design',
    icon: 'Palette',
    title: 'Branding & Logo Design',
    subtitle: 'New Logo. Or a Redesign. Done Right.',
    desc: 'Logo design or redesign, brand kits, UI/UX & marketing assets that make you look like a ₹1Cr company. We rebuilt Ankita Beauty Salon and built Grafiya from scratch.',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=900&q=80&auto=format&fit=crop',
    features: [
      'Logo design & redesigns',
      'Complete brand kits',
      'Social media templates',
      'Business cards & stationery',
      'Brand guidelines doc',
      'Unlimited revisions till you love it',
    ],
    price: 'Starting ₹1,999',
    timeline: '3–5 days',
    related: ['social-media-management', 'website-development'],
  },
  {
    slug: 'google-business-setup',
    icon: 'MapPin',
    title: 'Google Business Setup',
    subtitle: 'Create. Optimize. Dominate Local.',
    desc: 'Show up first when customers search for your service nearby. Complete Google Business Profile creation and optimization, plus local SEO.',
    image: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=900&q=80&auto=format&fit=crop',
    features: [
      'Profile creation & verification',
      'Photos, services & posts setup',
      'Review strategy',
      'Local SEO optimization',
      'Q&A section setup',
      'Maps ranking improvement',
    ],
    price: 'Starting ₹1,499',
    timeline: '1–2 days',
    related: ['website-development', 'meta-ads'],
  },
  {
    slug: 'meta-ads',
    icon: 'TrendingUp',
    title: 'Meta Ads & Performance Marketing',
    subtitle: 'Paid Reach. Real Results.',
    desc: 'Facebook & Instagram ad campaigns engineered for leads and sales — strategy, creatives, targeting and weekly optimization.',
    image: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=900&q=80&auto=format&fit=crop',
    features: [
      'Campaign strategy & setup',
      'Ad creative design',
      'Audience targeting & retargeting',
      'Pixel & conversion tracking',
      'A/B testing',
      'Weekly performance reports',
    ],
    price: 'Starting ₹4,999/mo + ad spend',
    timeline: 'Ongoing monthly',
    related: ['social-media-management', 'google-business-setup'],
  },
  {
    slug: 'app-development',
    icon: 'Smartphone',
    title: 'App Development',
    subtitle: 'iOS & Android. One Codebase.',
    desc: 'Cross-platform apps with React Native and Flutter. From MVP to full product — we ship apps users genuinely enjoy using.',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=900&q=80&auto=format&fit=crop',
    features: [
      'React Native / Flutter',
      'iOS & Android deployment',
      'REST API integration',
      'Push notifications',
      'App Store submission',
      'Performance optimization',
    ],
    price: 'Starting ₹24,999',
    timeline: '4–6 weeks',
    related: ['website-development', 'business-automation'],
  },
]

export const getService = (slug: string) => services.find((s) => s.slug === slug)

export const getRelated = (service: Service) =>
  (service.related ?? [])
    .map((slug) => getService(slug))
    .filter((s): s is Service => Boolean(s))
